### GET REQUEST
GET http://localhost:8080/api/1680122845399


### POST REQUEST
POST http://localhost:8080/api
content-type: application/json

{"Name": "Teddy",
"Number": 10}


### PUT REQUEST
PUT http://localhost:8080/api
content-type: application/json

{
	"hello":{"world"}
}

### DELETE REQUEST
DELETE http://localhost:8080/api/1680410292927