### GET REQUEST
GET http://localhost:8080/api/1680486694773


### POST REQUEST
POST http://localhost:8080/api
content-type: application/json

{
	"Name": "Tedla Tafari",
	"Age": 22
}


### PUT REQUEST
PUT http://localhost:8080/api/1680486694773
content-type: application/json

{
	"String": "Lulseged Admasu",
	"Int": 15,
	"Obj": {
		"type": "person", 
		"name": "lul",
		"talent": ["coding", "web design", "academia"]
	},
	"Array": [5, 1 , "string_v.2.0", 3]
}

### DELETE REQUEST
DELETE http://localhost:8080/api/644ad6d891bbc1951a04109d